Pages/Admin/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class CreateModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public CreateModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Member Member { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Members == null || Member == null)
            {
                return Page();
            }

            _context.Members.Add(Member);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class DeleteModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public DeleteModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Member Member { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FirstOrDefaultAsync(m => m.MemberId == id);

            if (member == null)
            {
                return NotFound();
            }
            else 
            {
                Member = member;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }
            var member = await _context.Members.FindAsync(id);

            if (member != null)
            {
                Member = member;
                _context.Members.Remove(Member);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class DetailsModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public DetailsModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public Member Member { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }
            else 
            {
                Member = member;
            }
            return Page();
        }
    }
}

Pages/ChurchGoals/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using outreach3.Data;
using outreach3.Data.Ministries;

namespace outreach3.Pages.ChurchGoals
{
    public class CreateModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public CreateModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      

        [BindProperty]
        public ChurchGoal ChurchGoal { get; set; } = default!;

        public string  ChurchName {get;set;}


        public IActionResult OnGet()
        {
            ChurchName = _context.Churches.FirstOrDefault(c => c.ChurchId == Convert.ToInt32(Request.Query["churchId"])).Name;

            return Page();

        }

            // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
            public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.ChurchGoals == null || ChurchGoal == null)
            {
                return Page();
            }

            ChurchGoal.ChurchId = Convert.ToInt32(Request.Query["churchId"]);

            _context.ChurchGoals.Add(ChurchGoal);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index", new { churchId = Request.Query["churchId"] });
        }
    }
}

Pages/ChurchGoals/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using outreach3.Data;
using outreach3.Data.Ministries;

namespace outreach3.Pages.ChurchGoals
{
    public class EditModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public EditModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ChurchGoal ChurchGoal { get; set; } = default!;

        public string DisplayError
        {
            get 
            {
                if(Error == "")
                {
                    return "none";
                }
                return "inline-block";
            }
        }
        public string Error { get; set; } = "";

    
      
        public string ErrorVisibility { get; set; } = "hidden";

        public List<SelectListItem> AllMissions { get; set; }
        public List<SelectListItem> GoalMissions { get; set; }

        public async Task<IActionResult> OnGetAsync(int? churchId, int? churchGoalId)
        {
            if (churchId == null || _context.ChurchGoals == null)
            {
                return NotFound();
            }

            var churchgoal =  await _context.ChurchGoals.FirstOrDefaultAsync(m => m.ChurchId == churchId && m.ChurchGoalId==churchGoalId);
            if (churchgoal == null)
            {
                return NotFound();
            }
            
            //churchgoal.ChurchId = Convert.ToInt32(Request.Query["churchId"]);
            ChurchGoal = churchgoal;

            AllMissions = _context.Missions.Where(m => m.ChurchId == churchId).Select(a =>
                                 new SelectListItem
                                 {
                                     Value = a.MissionId.ToString(),
                                     Text = a.Name
                                 }).ToList();


            GoalMissions = _context.Missions.Where(m => m.ChurchId == churchId && m.GoalId==churchgoal.ChurchGoalId).Select(a =>
                                 new SelectListItem
                                 {
                                     Value = a.MissionId.ToString(),
                                     Text = a.Name
                                 }).ToList();
            return Page();
        }




        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(ChurchGoal).State = EntityState.Modified;

            try
            {
                ChurchGoal.ChurchId = Convert.ToInt32(Request.Query["churchId"]);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ChurchGoalExists(ChurchGoal.ChurchGoalId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index", new { churchId = Request.Query["churchId"] });
        }

        public async Task<IActionResult> OnPostAddAsync(int churchGoalId)
        {
            var missionId = Convert.ToInt32(Request.Form["allMissions"]);
            if(missionId==0)
            {
                Error = "Please select a mission for this goal.";
                return null;
            }
            var missionGoalId = _context.Missions.FirstOrDefaultAsync(m => m.MissionId == missionId).Result.GoalId;

            if (missionGoalId != 0)
            {
                Error = "This Mission already belongs to a goal.";
                return null;
            }

            _context.Missions.FirstOrDefault(m => m.MissionId == missionId).GoalId = ChurchGoal.ChurchGoalId;
            ChurchGoal = _context.ChurchGoals.Where(m => m.ChurchGoalId == churchGoalId).FirstOrDefault();
            ChurchGoal.NumberOfDoorsGoal = ChurchGoal.NumberOfDoorsGoal + _context.Residents.Where(m => m.MissionId == missionId).Count();
            ChurchGoal.NumberOfGreetsGoal = ChurchGoal.NumberOfDoorsGoal / 4;
            await _context.SaveChangesAsync();    
            return RedirectToPage("Edit", new { churchId = Request.Query["churchId"], churchGoalId = Request.Query["churchGoalId"] });
        }
        public async Task<IActionResult> OnPostDeleteAsync(int churchGoalId)
        {
            var missionId = Convert.ToInt32(Request.Form["allMissions"]);

            if(missionId == 0)
            {
                Error = "Please select a mission from the Missions List (Top List).";
                return null;

            }

            if (missionId != 0)
            {
                var missionGoalId = _context.Missions.FirstOrDefaultAsync(m => m.MissionId == missionId).Result.GoalId;

                if (missionGoalId != churchGoalId)
                {
                    Error = "This Mission cannot be removed, it is not part of this goal.";
                    return null;
                }


                _context.Missions.FirstOrDefaultAsync(m => m.MissionId == missionId).Result.GoalId = 0;
                ChurchGoal = _context.ChurchGoals.Where(m => m.ChurchGoalId == churchGoalId).FirstOrDefault();
                ChurchGoal.NumberOfDoorsGoal = ChurchGoal.NumberOfDoorsGoal - _context.Residents.Where(m => m.MissionId == missionId).Count();
                ChurchGoal.NumberOfGreetsGoal = ChurchGoal.NumberOfDoorsGoal / 4;
            }

            await _context.SaveChangesAsync();
            return RedirectToPage("Edit", new { churchId = Request.Query["churchId"], churchGoalId = Request.Query["churchGoalId"] });
        }
        public async Task<IActionResult> OnPostResetAsync(int churchGoalId)
        {
            
            foreach(var mission in _context.Missions.Where(m=>m.GoalId==churchGoalId))
            {
                mission.GoalId = 0;
            }

            ChurchGoal = _context.ChurchGoals.Where(m => m.ChurchGoalId == churchGoalId).FirstOrDefault();
            ChurchGoal.NumberOfDoorsGoal = 0;
            ChurchGoal.NumberOfGreetsGoal = 0;
            await _context.SaveChangesAsync();
            return RedirectToPage("Edit", new { churchId = Request.Query["churchId"], churchGoalId = Request.Query["churchGoalId"] });
        }

        public async Task<IActionResult> OnPostOKAsync(int churchGoalId, int churchId)
        {           
            return RedirectToPage("Edit", new { churchId, churchGoalId });
        }

        private bool ChurchGoalExists(int id)
        {
          return (_context.ChurchGoals?.Any(e => e.ChurchGoalId == id)).GetValueOrDefault();
        }
    }
}

Pages/Members/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Members
{
    public class EditModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;
        private IServiceProvider _serviceProvider;

        public EditModel(outreach3.Data.ApplicationDbContext context, IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
            _context = context;
        }

        [BindProperty]
        public Member Member { get; set; } = default!;


        [BindProperty]
        public List<Church> Churches { get; set; } = default!;



        public async Task<IActionResult> OnGetAsync(int memberId)
        {
            if (memberId == null || _context.Members == null)
            {
                return NotFound();
            }

            var member =  await _context.Members.FirstOrDefaultAsync(m => m.MemberId == memberId);
            if (member == null)
            {
                return NotFound();
            }
            Member = member;

            
          

            

           

            Churches = await _context.Churches.ToListAsync();


            

          

            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Member).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MemberExists(Member.MemberId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        [BindProperty]
        public Church SelectedChurch { get; set; }



        public async Task<IActionResult> OnPostRemoveAsync(int memberId)
        {
            if (!ModelState.IsValid) 
            {
                return NotFound();
            }
            _context.Members.FirstOrDefault(m => m.MemberId == memberId).ChurchId = 0;
            await _context.SaveChangesAsync();

            return RedirectToPage("./Edit", new { memberId = Member.MemberId, churchId=SelectedChurch.ChurchId });
        }


        public async Task<IActionResult> OnPostAddAsync(int memberId, int churchId)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }
            _context.Members.FirstOrDefault(m => m.MemberId == memberId).ChurchId = churchId;
            await _context.SaveChangesAsync();
            return RedirectToPage("./Edit", new { memberId = Member.MemberId, churchId = churchId });
        }

        public async Task<IActionResult> OnPostRemoveAccountAsync(int memberId, int churchId)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }
            var member = _context.Members.FirstOrDefault(m => m.MemberId == memberId);
            var email = member.Email;
            _context.Members.Remove(member);


            var _userManager = _serviceProvider.GetRequiredService<UserManager<IdentityUser>>();
            var user = await _userManager.FindByEmailAsync(email);




            var rolesForUser = await _userManager.GetRolesAsync(user);

            using (var transaction = _context.Database.BeginTransaction())
            {
                if (rolesForUser.Count() > 0)
                {
                    foreach (var item in rolesForUser.ToList())
                    {
                        // item should be the name of the role
                        var result = await _userManager.RemoveFromRoleAsync(user, item);
                    }
                }

                await _userManager.DeleteAsync(user);
                transaction.Commit();
            }



            await _context.SaveChangesAsync();
            return RedirectToPage("../Admin/AllUsers", new { memberId = Member.MemberId, churchId = churchId });
        }

        private bool MemberExists(int id)
        {
          return (_context.Members?.Any(e => e.MemberId == id)).GetValueOrDefault();
        }
    }
}

Pages/Members/Create.cshtml
@page
@model outreach3.Pages.Members.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Member.Name" class="control-label"></label>
                <input asp-for="Member.Name" class="form-control" />
                <span asp-validation-for="Member.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Member.Email" class="control-label"></label>
                <input asp-for="Member.Email" class="form-control" />
                <span asp-validation-for="Member.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Members/Delete.cshtml
@page
@model outreach3.Pages.Members.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Member.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Member.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Member.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Member.Email)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Member.MemberId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Members/Details.cshtml
@page
@model outreach3.Pages.Members.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<table style="width:100%;">
    <tr>
        <td>
        </td>


        <td>
            <div>
                <h4>All Churches</h4>
                <hr />
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Churches)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Churches)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Churches)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Churches)
                    </dd>
                </dl>
            </div>
        </td>

        <td>
            <div>
                <h4>Member</h4>
                <hr />
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Member.Name)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Member.Name)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Member.Email)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Member.Email)
                    </dd>
                </dl>
            </div>
        </td>


    </tr>
</table>

<div>
    <a asp-page="./Edit" asp-route-id="@Model.Member?.MemberId">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Members/Edit.cshtml
@page
@model outreach3.Pages.Members.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h4>Member</h4>
<div class="rightDiv">
    <a asp-page="./Index">Return to Users</a>
</div>

<hr />
<div class="row">
    <div class="col-md-8">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Member.MemberId" />
            <div class="form-group">
                <label asp-for="Member.Name" class="control-label"></label>
                <input asp-for="Member.Name" class="form-control" />
                <span asp-validation-for="Member.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Member.Email" class="control-label"></label>
                <input asp-for="Member.Email" class="form-control" />
                <span asp-validation-for="Member.Email" class="text-danger"></span>
            </div>
            <p>
                <br/>
            <button onclick="return(ensure())" class="btn-danger" formmethod="post" asp-page="./Edit" asp-page-handler="RemoveAccount" asp-route-churchId="@Request.Query["churchId"]" asp-route-memberId="@Model.Member.MemberId">Remove Account</button>
            </p>
            <table style="border:1px black outset;">
                <tr>
                    <td style="vertical-align:top;">
                        <table style="vertical-align:top;">

                            <tbody>

                                <tr>
                                    <th style="vertical-align:top;font-weight:bold;text-decoration:underline">
                                        All Churches
                                    </th>
                                </tr>
                                @foreach (var item in Model.Churches)
                                {
                                    <tr>
                                        <td style="vertical-align:top;">
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>

                                        <td style="vertical-align:top;">
                                            <button style="border:none" formmethod="post" asp-page="./Edit" asp-page-handler="Add" asp-route-churchId="@item.ChurchId"  asp-route-memberId="@Model.Member.MemberId">Select</button>
                                        </td>

                                    </tr>
                                }

                            </tbody>
                        </table>
                    </td>
                    <td style="width:12px;"></td>
                    <td style="vertical-align:top;">
                        <table style="vertical-align:top;">

                            <tbody>
                                <tr>
                                    <th style="vertical-align:top;font-weight:bold;text-decoration:underline">
                                        Member's Church
                                    </th>
                                </tr>
                                

                                @foreach (var item in Model.Churches.Where(c=>c.ChurchId==Convert.ToInt32(Request.Query["churchId"])))
                                {
                                    <tr>
                                        <td style="vertical-align:top;text-align:center;">
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </td>
                    <td style="width:24px;"></td>

                    
                </tr>
            </table>
        </form>

    </div>
</div>

<script>
    function ensure()
    {
       var conf =  confirm("Are you sure you want to delete this account?");
      return(conf);
    }

</script>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Pages/Members/Index.cshtml
@page
@model outreach3.Pages.Members.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h4>Approve Membership</h4>
<div class="rightDiv shadow">
    <a asp-page="../Admin/AdminMenu">Return to Menu</a>
</div>
<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Members[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Members[0].Email)
                </th>
                <th>Approved</th>                
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Members)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        <input asp-for="@item.Approved" type="checkbox" name="checkBoxChurchMember" value="@item.MemberId" />
                    </td>
                    
                </tr>
            }
        </tbody>
    </table>

    <div class=" rightDiv">
        <input class="shadow" type="submit" value="Save" asp-page-handler="Approve" />
    </div>
</form>
<script>

   

</script>