Pages/Admin/AdminMenu.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using outreach3.Data;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class AdminMenuModel : PageModel
    {

        private readonly ApplicationDbContext _context;

        public AdminMenuModel(ApplicationDbContext context)
        {
            _context = context;
        }


        public List<Church> Churches = new List<Church>();      

        public void OnGet()
        {
           Churches =  _context.Churches.ToList();
        }
    }
}

Pages/Admin/AllUsers.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using outreach3.Data;
using outreach3.Data.Ministries;
using System.Data;
using IdentityRole = Microsoft.AspNetCore.Identity.IdentityRole;

namespace outreach3.Pages.Admin
{
    public class AllUsersModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private IServiceProvider _serviceProvider;
        
       
      
        public AllUsersModel(ApplicationDbContext context, IServiceProvider serviceProvider)
        {
            _context = context;
            _serviceProvider = serviceProvider;
        }

        public List<Church> Churches { get; set; }
        public List<Member> Members { get; set; } = new List<Member>();
      

        public async Task<IActionResult> OnGetAsync()
        {   
            Churches = await _context.Churches.ToListAsync();
            Members = await _context.Members.ToListAsync();
            return Page();
        }

      





        private bool MemberExists(int id)
        {
          return (_context.Members?.Any(e => e.MemberId == id)).GetValueOrDefault();
        }

      
    }
}

Pages/Admin/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class CreateModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public CreateModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Member Member { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Members == null || Member == null)
            {
                return Page();
            }

            _context.Members.Add(Member);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class DeleteModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public DeleteModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Member Member { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FirstOrDefaultAsync(m => m.MemberId == id);

            if (member == null)
            {
                return NotFound();
            }
            else 
            {
                Member = member;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }
            var member = await _context.Members.FindAsync(id);

            if (member != null)
            {
                Member = member;
                _context.Members.Remove(Member);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class DetailsModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public DetailsModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public Member Member { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }
            else 
            {
                Member = member;
            }
            return Page();
        }
    }
}

Pages/Admin/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class EditModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public EditModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Member Member { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member =  await _context.Members.FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }
            Member = member;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Member).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MemberExists(Member.MemberId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool MemberExists(int id)
        {
          return (_context.Members?.Any(e => e.MemberId == id)).GetValueOrDefault();
        }
    }
}

Pages/Admin/EditUsers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace outreach3.Pages.Admin
{
    public class EditUsersModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Admin/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class IndexModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public IndexModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Member> Member { get;set; } = default!;

        public async Task OnGetAsync()
        {
            if (_context.Members != null)
            {
                Member = await _context.Members.ToListAsync();
            }
        }
    }
}

Pages/Admin/RoleUsers.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using outreach3.Data;
using outreach3.Data.Ministries;
using IdentityRole = Microsoft.AspNetCore.Identity.IdentityRole;

namespace outreach3.Pages.Admin
{
    public class RoleUsersModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private IServiceProvider _serviceProvider;
        
       
      
        public RoleUsersModel(ApplicationDbContext context, IServiceProvider serviceProvider)
        {
            _context = context;
            _serviceProvider = serviceProvider;
        }


        public List<Member> Members { get; set; } = new List<Member>();

        public IList<IdentityUser> Users { get; set; } = new List<IdentityUser>();

        public List<IdentityRole> AllRoles { get; set; } = new List<IdentityRole>();

    
        public async Task<IActionResult> OnGetAsync()
        {
            await GetAllRoles();
           
            return Page();
        }



        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostSelectRoleAsync(string role)
        {
            await GetAllRoles();
            var userManager = _serviceProvider.GetRequiredService<Microsoft.AspNetCore.Identity.UserManager<Microsoft.AspNetCore.Identity.IdentityUser>>();
            Users = await userManager.GetUsersInRoleAsync(role);

            return Page();
        }

           

        private async Task GetAllRoles()
        {
            var roleManager = _serviceProvider.GetRequiredService<Microsoft.AspNetCore.Identity.RoleManager<Microsoft.AspNetCore.Identity.IdentityRole>>();
            AllRoles = roleManager.Roles.ToList();
          
        }





        private bool MemberExists(int id)
        {
          return (_context.Members?.Any(e => e.MemberId == id)).GetValueOrDefault();
        }

      
    }
}

Pages/Admin/UserRoles.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using outreach3.Data;
using outreach3.Data.Ministries;
using System.Data;
using IdentityRole = Microsoft.AspNetCore.Identity.IdentityRole;

namespace outreach3.Pages.Admin
{
    public class UserRolesModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private IServiceProvider _serviceProvider;
        
       
      
        public UserRolesModel(ApplicationDbContext context, IServiceProvider serviceProvider)
        {
            _context = context;
            _serviceProvider = serviceProvider;
        }

        public List<Church> Churches { get; set; }
        public List<Member> Members { get; set; } = new List<Member>();
        public List<string> AllRoles { get; set; } = new List<string>();

        public List<string> UserRoles { get; set; } = new List<string>();

        public int SelectedChurchId { get; set; } 
        public int SelectedMemberId { get; set; }
        public string SelectedRole { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {   
            Churches = _context.Churches.ToList();           
            return Page();
        }

        public async Task<IActionResult> OnPostSelectedChurchAsync(int churchId)
        {
            Churches = _context.Churches.ToList();
            SelectedChurchId = churchId;
            Members = await _context.Members.Where(m=>m.ChurchId == churchId).ToListAsync();
            return Page();
        }


        public async Task<IActionResult> OnPostSelectedMemberAsync(int churchId, int memberId)
        {

            Churches = _context.Churches.ToList();
            SelectedChurchId = churchId;
            Members = await _context.Members.Where(m => m.ChurchId == churchId).ToListAsync();
            SelectedMemberId = memberId;
            AllRoles = await GetAllRoles();
            UserRoles = await GetUserRoles(memberId);
            return Page();
        }

        private async Task<List<string>> GetUserRoles(int memberId)
        {
            var userManager = _serviceProvider.GetRequiredService<Microsoft.AspNetCore.Identity.UserManager<Microsoft.AspNetCore.Identity.IdentityUser>>();
            var roleManager = _serviceProvider.GetRequiredService<Microsoft.AspNetCore.Identity.RoleManager<Microsoft.AspNetCore.Identity.IdentityRole>>();
            var selectedMemberEmail = _context.Members.FirstOrDefault(m => m.MemberId == memberId).Email;
            var user = userManager.Users.FirstOrDefault(u => u.Email == selectedMemberEmail);

            
            var roles = await userManager.GetRolesAsync(user);

            return roles.ToList();
          
        }






        public async Task<IActionResult> OnPostRemoveRoleAsync(int churchId, int memberId, string role)
        {
            Churches = _context.Churches.ToList();
            SelectedChurchId = churchId;
            Members = await _context.Members.Where(m => m.ChurchId == churchId).ToListAsync();
            SelectedMemberId = memberId;
            AllRoles = await GetAllRoles();

            var userManager = _serviceProvider.GetRequiredService<Microsoft.AspNetCore.Identity.UserManager<Microsoft.AspNetCore.Identity.IdentityUser>>();
            var roleManager = _serviceProvider.GetRequiredService<Microsoft.AspNetCore.Identity.RoleManager<Microsoft.AspNetCore.Identity.IdentityRole>>();
            var selectedMemberEmail = _context.Members.FirstOrDefault(m => m.MemberId == memberId).Email;
            var user = userManager.Users.FirstOrDefault(u => u.Email == selectedMemberEmail);



            await userManager.RemoveFromRoleAsync(user, role);
            await _context.SaveChangesAsync();
            UserRoles = await GetUserRoles(memberId);

            return Page();
        }

        public async Task<IActionResult> OnPostAddRoleAsync(int churchId, int memberId, string role)
        {
            Churches = _context.Churches.ToList();
            SelectedChurchId = churchId;
            Members = await _context.Members.Where(m => m.ChurchId == churchId).ToListAsync();
            SelectedMemberId = memberId;
            AllRoles = await GetAllRoles();

            var userManager = _serviceProvider.GetRequiredService<Microsoft.AspNetCore.Identity.UserManager<Microsoft.AspNetCore.Identity.IdentityUser>>();
            var roleManager = _serviceProvider.GetRequiredService<Microsoft.AspNetCore.Identity.RoleManager<Microsoft.AspNetCore.Identity.IdentityRole>>();
            var selectedMemberEmail = _context.Members.FirstOrDefault(m => m.MemberId == memberId).Email;
            var user = userManager.Users.FirstOrDefault(u => u.Email == selectedMemberEmail);
                        
            
           
            await userManager.AddToRoleAsync(user, role);            
            await _context.SaveChangesAsync();
            UserRoles = await GetUserRoles(memberId);

            return Page();
        }



      

     

      
        private async Task GetMembersAsync()
        {
            Members = await _context.Members.ToListAsync();            
        }


        private async Task<List<string>> GetAllRoles()
        {
           return await  _serviceProvider.GetRequiredService<RoleManager<IdentityRole>>().Roles.Select(r => r.Name).ToListAsync();
        }





        private bool MemberExists(int id)
        {
          return (_context.Members?.Any(e => e.MemberId == id)).GetValueOrDefault();
        }

      
    }
}

Pages/Admin/AdminMenu.cshtml
@page
@model outreach3.Pages.Admin.AdminMenuModel


<h4> Admin Menu</h4>


<table class="table">
    <thead>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        <tr>
            <td>
                <a class="linkInput" asp-page="/Members/Index">Approve Church Members</a>
            </td>

            <td>
                @if (User.IsInRole("Admin"))
                {
                    <a  class="linkInput" asp-page="./UserRoles">Assign User Roles</a>
                }
            </td>
            <td>
                @if (User.IsInRole("Admin"))
                {
                    <a class="linkInput" asp-page="./RoleUsers">View Roles by User</a>
                }
            </td>
            <td>
                @if (User.IsInRole("Admin"))
                {
                    <a class="linkInput" asp-page="./AllUsers">Edit Users</a>
                }
            </td>
            <td>
                @if (User.IsInRole("Admin") || User.IsInRole("ChurchAdmin"))
                {
                    <table>
                        <tr><td colspan="3">Set Goals<hr /></td></tr>
                    @foreach (var church in Model.Churches)
                    {
                        <tr>
                            <td>@church.Name</td><td style="width:20px;"></td>
                            <td><a asp-page="../ChurchGoals/Index" asp-route-churchId="@church.ChurchId">Set Goals</a></td>
                        </tr>

                    }
                    </table>
                }
            </td>
            
        </tr>

    </tbody>
</table>

Pages/Admin/AllUsers.cshtml
@page
@model outreach3.Pages.Admin.AllUsersModel
@inject IServiceProvider Service;
@{
    ViewData["Title"] = "Users";
}

<h4>Users</h4>
<div class="rightDiv">
    <a asp-page="./AdminMenu">Return to Menu</a>
</div>
<hr />

   
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            @foreach (var church in Model.Churches)
            {
                
                <table class="table7">
                    <thead>
                        <tr><td colspan="4"><div class="selectChurchHeader2">@church.ChurchFullName</div></td></tr>
                        <tr>
                            <td class="td7">User Name</td>
                            <td class="td7">E-Mail></td>
                            <td class="td7">Edit</td>
                        </tr>
                    </thead>
                    @foreach (var member in Model.Members.Where(m => m.ChurchId == church.ChurchId))
                    {
                        <tr>
                            <td>@member.Name</td>
                            <td>@member.Email</td>
                            <td><a asp-page="../Members/Edit" asp-route-churchId="@member.ChurchId" asp-route-memberId="@member.MemberId">Edit</a></td>
                        </tr>

                    }
                </table>
                <br/><br/>
            }
        </form>



        @section Scripts {
            @{
                await Html.RenderPartialAsync("_ValidationScriptsPartial");
            }
        }

Pages/Admin/Create.cshtml
@page
@model outreach3.Pages.Admin.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Member.Name" class="control-label"></label>
                <input asp-for="Member.Name" class="form-control" />
                <span asp-validation-for="Member.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Member.Email" class="control-label"></label>
                <input asp-for="Member.Email" class="form-control" />
                <span asp-validation-for="Member.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Admin/Delete.cshtml
@page
@model outreach3.Pages.Admin.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Member.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Member.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Member.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Member.Email)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Member.MemberId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Admin/Details.cshtml
@page
@model outreach3.Pages.Admin.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Member.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Member.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Member.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Member.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Member?.MemberId">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Admin/EditUsers.cshtml
@page
@model outreach3.Pages.Admin.EditUsersModel
@{
}

Pages/Admin/RoleUsers.cshtml
@page
@model outreach3.Pages.Admin.RoleUsersModel
@inject IServiceProvider Service;
@{
    ViewData["Title"] = "UserRoles";
}

<h4>UserRoles</h4>
<div class="rightDiv">
    <a asp-page="./AdminMenu">Return to Menu</a>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <table>
                <tr style="vertical-align:top;">
                    <td>
                        <div class="selectRoles">
                            <div class="selectChurchHeader">All Roles</div><hr />
                            
                                @foreach (var role in Model.AllRoles)
                                {
                                    <span class="linkInput">

                                    <input class="linkInputDark" type="submit" asp-page-handler="SelectRole" asp-route-role="@role.ToString()" value="@role.ToString()">
                                    </span> <br />
                                }
                           
                        </div>
                    </td>
                  
                   
                     <td>
                        <div class="selectRoles">
                            <div class="selectChurchHeader">Users</div><hr />
                            
                                @foreach (var user in Model.Users)
                                {
                                            <span class="linkInput">
                                            <input class="linkInputDark" type="submit" value="@user.UserName" /></span> <br/>

                                }

                            
                        </div>     
                    </td>
                </tr>
            </table>   
             <input type="hidden" name=selectedChurch />
             <input type="hidden" name="inpRemoveRoleUser" />
             <input type="hidden" name="inpRemoveRoleRole" />
              <input type="hidden" name="inpAddRoleUser" />
             <input type="hidden" name="inpAddRoleRole" />
        
         </form>
    </div>
</div>

<script>
 
    function removeRoleFromUser(u, r)
    {        
        document.getElementsByName("inpRemoveRoleUser")[0].value = u;
        document.getElementsByName("inpRemoveRoleRole")[0].value = r;
    }
    
    function addRoleToUser(u, r)
    {   
        document.getElementsByName("inpAddRoleUser")[0].value = u;
        document.getElementsByName("inpAddRoleRole")[0].value = r;
    }


</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Admin/UserRoles.cshtml
@page
@model outreach3.Pages.Admin.UserRolesModel
@inject IServiceProvider Service;
@{
    ViewData["Title"] = "UserRoles";
}

<h4>UserRoles</h4>
<div class="rightDiv">
    <a asp-page="./AdminMenu">Return to Menu</a>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <table>
                <tr style="vertical-align:top;">     
                    <td>
                        
                              
                        <div class="selectChurch">
                            <div class="selectChurchHeader"> Select a Church</div>
                            <hr />
                            @foreach (var church in Model.Churches)
                            {

                                @if (Request.Query["churchId"] == @church.ChurchId.ToString())
                                {
                                    <p>
                                        <input class="shadowGreen" type="submit" asp-route-churchId="@church.ChurchId" asp-page-handler="SelectedChurch" value="@church.Name" />
                                    </p>
                                }
                                else
                                {
                                    <p>
                                        <input class="shadow" type="submit" asp-route-churchId="@church.ChurchId" asp-page-handler="SelectedChurch" value="@church.Name" />
                                    </p>
                                }

                               
                            }                            
                        </div>

                                
                    </td>

                    <td>                        
                       <div class="selectChurch">    
                            <div class="selectChurchHeader"> Select a Member</div><hr />
                           
                                @foreach(var member in Model.Members)
                                {
                                    
                                var selectedLink = "shadow";
                                @if(Request.Query["memberId"]==member.MemberId.ToString())
                                {
                                    selectedLink = "shadowGreen";
                                }
                                            <input class="@selectedLink" type="submit" asp-route-churchId="@Model.SelectedChurchId" asp-route-memberId="@member.MemberId" asp-page-handler="SelectedMember" value="@member.Name"  />
                                           

                                    <br/>
                                }
                          
                        </div>         
                    </td>
                    
                    <td>
                          <div class="selectChurchLeft">    
                            <div class="selectChurchHeader">Select a Role</div><hr />                            
                                @foreach(var role in Model.AllRoles)
                                {
                                    <span class="linkInput">@role.ToString()
                                            <input asp-route-churchId="@Model.SelectedChurchId" asp-route-memberId="@Model.SelectedMemberId" asp-route-role="@role" class="linkInputDark" type="submit" asp-page-handler="AddRole" value="Add"></span> <br/>
                                }                            
                        </div>     
                    </td>
                     <td>
                          <div class="selectChurchLeft">    
                            <div class="selectChurchHeader">User Roles</div><hr />
                                @foreach (var role in Model.UserRoles)
                                {
                                            <span class="linkInput">@role.ToString()
                                        <input asp-route-churchId="@Model.SelectedChurchId" asp-route-memberId="@Model.SelectedMemberId" asp-route-role="@role" class="linkInputDark" type="submit" asp-page-handler="RemoveRole" value="Remove">
                                    </span> <br />

                                }
                        </div>     
                    </td>
                </tr>
            </table>   
             <input type="hidden" name=selectedChurch />
             <input type="hidden" name="inpRemoveRoleUser" />
             <input type="hidden" name="inpRemoveRoleRole" />
              <input type="hidden" name="inpAddRoleUser" />
             <input type="hidden" name="inpAddRoleRole" />
        
         </form>
    </div>
</div>

<script>
 
    function removeRoleFromUser(u, r)
    {        
        document.getElementsByName("inpRemoveRoleUser")[0].value = u;
        document.getElementsByName("inpRemoveRoleRole")[0].value = r;
    }
    
    function addRoleToUser(u, r)
    {   
        document.getElementsByName("inpAddRoleUser")[0].value = u;
        document.getElementsByName("inpAddRoleRole")[0].value = r;
    }


</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}