Pages/Admin/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class CreateModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public CreateModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Member Member { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Members == null || Member == null)
            {
                return Page();
            }

            _context.Members.Add(Member);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class DeleteModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public DeleteModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Member Member { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FirstOrDefaultAsync(m => m.MemberId == id);

            if (member == null)
            {
                return NotFound();
            }
            else 
            {
                Member = member;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }
            var member = await _context.Members.FindAsync(id);

            if (member != null)
            {
                Member = member;
                _context.Members.Remove(Member);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class DetailsModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public DetailsModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public Member Member { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }
            else 
            {
                Member = member;
            }
            return Page();
        }
    }
}

Pages/Admin/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class EditModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public EditModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Member Member { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member =  await _context.Members.FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }
            Member = member;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Member).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MemberExists(Member.MemberId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool MemberExists(int id)
        {
          return (_context.Members?.Any(e => e.MemberId == id)).GetValueOrDefault();
        }
    }
}

Pages/ChurchGoals/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using outreach3.Data;
using outreach3.Data.Ministries;

namespace outreach3.Pages.ChurchGoals
{
    public class EditModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public EditModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ChurchGoal ChurchGoal { get; set; } = default!;

        public string DisplayError
        {
            get 
            {
                if(Error == "")
                {
                    return "none";
                }
                return "inline-block";
            }
        }
        public string Error { get; set; } = "";

    
      
        public string ErrorVisibility { get; set; } = "hidden";

        public List<SelectListItem> AllMissions { get; set; }
        public List<SelectListItem> GoalMissions { get; set; }

        public async Task<IActionResult> OnGetAsync(int? churchId, int? churchGoalId)
        {
            if (churchId == null || _context.ChurchGoals == null)
            {
                return NotFound();
            }

            var churchgoal =  await _context.ChurchGoals.FirstOrDefaultAsync(m => m.ChurchId == churchId && m.ChurchGoalId==churchGoalId);
            if (churchgoal == null)
            {
                return NotFound();
            }
            
            //churchgoal.ChurchId = Convert.ToInt32(Request.Query["churchId"]);
            ChurchGoal = churchgoal;

            AllMissions = _context.Missions.Where(m => m.ChurchId == churchId).Select(a =>
                                 new SelectListItem
                                 {
                                     Value = a.MissionId.ToString(),
                                     Text = a.Name
                                 }).ToList();


            GoalMissions = _context.Missions.Where(m => m.ChurchId == churchId && m.GoalId==churchgoal.ChurchGoalId).Select(a =>
                                 new SelectListItem
                                 {
                                     Value = a.MissionId.ToString(),
                                     Text = a.Name
                                 }).ToList();
            return Page();
        }




        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(ChurchGoal).State = EntityState.Modified;

            try
            {
                ChurchGoal.ChurchId = Convert.ToInt32(Request.Query["churchId"]);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ChurchGoalExists(ChurchGoal.ChurchGoalId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index", new { churchId = Request.Query["churchId"] });
        }

        public async Task<IActionResult> OnPostAddAsync(int churchGoalId)
        {
            var missionId = Convert.ToInt32(Request.Form["allMissions"]);
            if(missionId==0)
            {
                Error = "Please select a mission for this goal.";
                return null;
            }
            var missionGoalId = _context.Missions.FirstOrDefaultAsync(m => m.MissionId == missionId).Result.GoalId;

            if (missionGoalId != 0)
            {
                Error = "This Mission already belongs to a goal.";
                return null;
            }

            _context.Missions.FirstOrDefault(m => m.MissionId == missionId).GoalId = ChurchGoal.ChurchGoalId;
            ChurchGoal = _context.ChurchGoals.Where(m => m.ChurchGoalId == churchGoalId).FirstOrDefault();
            ChurchGoal.NumberOfDoorsGoal = ChurchGoal.NumberOfDoorsGoal + _context.Residents.Where(m => m.MissionId == missionId).Count();
            ChurchGoal.NumberOfGreetsGoal = ChurchGoal.NumberOfDoorsGoal / 4;
            await _context.SaveChangesAsync();    
            return RedirectToPage("Edit", new { churchId = Request.Query["churchId"], churchGoalId = Request.Query["churchGoalId"] });
        }
        public async Task<IActionResult> OnPostDeleteAsync(int churchGoalId)
        {
            var missionId = Convert.ToInt32(Request.Form["allMissions"]);

            if(missionId == 0)
            {
                Error = "Please select a mission from the Missions List (Top List).";
                return null;

            }

            if (missionId != 0)
            {
                var missionGoalId = _context.Missions.FirstOrDefaultAsync(m => m.MissionId == missionId).Result.GoalId;

                if (missionGoalId != churchGoalId)
                {
                    Error = "This Mission cannot be removed, it is not part of this goal.";
                    return null;
                }


                _context.Missions.FirstOrDefaultAsync(m => m.MissionId == missionId).Result.GoalId = 0;
                ChurchGoal = _context.ChurchGoals.Where(m => m.ChurchGoalId == churchGoalId).FirstOrDefault();
                ChurchGoal.NumberOfDoorsGoal = ChurchGoal.NumberOfDoorsGoal - _context.Residents.Where(m => m.MissionId == missionId).Count();
                ChurchGoal.NumberOfGreetsGoal = ChurchGoal.NumberOfDoorsGoal / 4;
            }

            await _context.SaveChangesAsync();
            return RedirectToPage("Edit", new { churchId = Request.Query["churchId"], churchGoalId = Request.Query["churchGoalId"] });
        }
        public async Task<IActionResult> OnPostResetAsync(int churchGoalId)
        {
            
            foreach(var mission in _context.Missions.Where(m=>m.GoalId==churchGoalId))
            {
                mission.GoalId = 0;
            }

            ChurchGoal = _context.ChurchGoals.Where(m => m.ChurchGoalId == churchGoalId).FirstOrDefault();
            ChurchGoal.NumberOfDoorsGoal = 0;
            ChurchGoal.NumberOfGreetsGoal = 0;
            await _context.SaveChangesAsync();
            return RedirectToPage("Edit", new { churchId = Request.Query["churchId"], churchGoalId = Request.Query["churchGoalId"] });
        }

        public async Task<IActionResult> OnPostOKAsync(int churchGoalId, int churchId)
        {           
            return RedirectToPage("Edit", new { churchId, churchGoalId });
        }

        private bool ChurchGoalExists(int id)
        {
          return (_context.ChurchGoals?.Any(e => e.ChurchGoalId == id)).GetValueOrDefault();
        }
    }
}

Pages/ChurchGoals/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using outreach3.Data;
using outreach3.Data.Ministries;
using outreach3.Pages.Missions;

namespace outreach3.Pages.ChurchGoals
{
    public class IndexModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<IdentityUser> _manager;
        public IndexModel(outreach3.Data.ApplicationDbContext context, UserManager<IdentityUser> manager, IEmailSender emailSender, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _manager = manager;
            _emailSender = emailSender;
            _webHostEnvironment= webHostEnvironment;
        }

        public IList<ChurchGoal> ChurchGoals { get; set; } = default!;
        public string EmailNotificationAdd { get; private set; }
        public string EmailNotificationRemove { get; private set; }

        public async Task OnGetAsync()
        {
            if (_context.ChurchGoals != null)
            {
                var churchId = Convert.ToInt32(Request.Query["churchId"]);
                var churchGoalIds = await _context.ChurchGoals.Select(c => c.ChurchGoalId).ToListAsync();


                ChurchGoals = await _context.ChurchGoals.Where(g => g.ChurchId == churchId).ToListAsync();

                var visitationCount = 0;
                var visitationGreets = 0;
                foreach (var churchGoal in ChurchGoals)
                {
                    var missionIds = await _context.Missions.Where(v => v.GoalId == churchGoal.ChurchGoalId).Select(m => m.MissionId).ToListAsync();

                    foreach (var missionId in missionIds)
                    {
                        visitationCount += _context.Visitations.Where(v => v.MissionId == missionId).Count();
                        visitationGreets += _context.Visitations.Where(v => v.VisitationType == TypeVisit.Greeted && v.MissionId == missionId).Count();

                    }
                    churchGoal.NumberOfDoors = visitationCount;
                    await _context.SaveChangesAsync();

                    await SetEmailNotificationLinks(churchId);

                }
            }
        }

        private async Task SetEmailNotificationLinks(int churchId)
        {
            var usr = await _manager.GetUserAsync(HttpContext.User);
            var email = usr?.Email;
            var memberId = _context.Members.FirstOrDefault(m => m.Email == email)?.MemberId;

            if (_context.ChurchMembers.FirstOrDefault(c => c.MemberId == memberId && c.ChurchId == churchId) == null)
            {
                EmailNotificationAdd = "in-line-block";
                EmailNotificationRemove = "none";
            }
            else
            {
                EmailNotificationAdd = "none";
                EmailNotificationRemove = "in-line-block";
            }
        }

        public async Task<IActionResult> OnPostAddEmailAsync(int churchId)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            var usr = await _manager.GetUserAsync(HttpContext.User);
            var email = usr?.Email;
            var memberId = _context.Members.FirstOrDefault(m => m.Email == email).MemberId;

            if (_context.ChurchMembers.FirstOrDefault(c => c.MemberId == memberId && c.ChurchId == churchId) == null)
            {
                var churchMember = new ChurchMembers { ChurchId = churchId , MemberId = memberId};
                _context.ChurchMembers.Add(churchMember);
                await _context.SaveChangesAsync();
            }         

            return  RedirectToPage("./Index", new { churchId = Request.Query["churchId"] });
        }


        public async Task<IActionResult> OnPostRemoveEmailAsync(int churchId)
        {
           
            var usr = await _manager.GetUserAsync(HttpContext.User);
            var email = usr?.Email;
            var memberId = _context.Members.FirstOrDefault(m => m.Email == email).MemberId;


            _context.ChurchMembers.Where(c => c.MemberId == memberId && c.ChurchId == churchId).ExecuteDelete();

            await _context.SaveChangesAsync();
            return RedirectToPage("./Index", new { churchId = Request.Query["churchId"] });
        }

    }
}

Pages/ChurchGoals/Create.cshtml
@page
@model outreach3.Pages.ChurchGoals.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ChurchGoal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">

            <h6>     @Model.ChurchName;</h6><hr />
                
            <div class="form-group">
                <label asp-for="ChurchGoal.Name" class="control-label"></label>
                <input asp-for="ChurchGoal.Name" class="form-control" />
                <span asp-validation-for="ChurchGoal.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChurchGoal.StartDate" class="control-label"></label>
                <input asp-for="ChurchGoal.StartDate" class="form-control" />
                <span asp-validation-for="ChurchGoal.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChurchGoal.GoalDate" class="control-label"></label>
                <input asp-for="ChurchGoal.GoalDate" class="form-control" />
                <span asp-validation-for="ChurchGoal.GoalDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" asp-route-churchId="@Request.Query["churchId"]" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index" asp-route-churchId="@Request.Query["churchId"]">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/ChurchGoals/Delete.cshtml
@page
@model outreach3.Pages.ChurchGoals.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ChurchGoal</h4>
    <hr />

    <div class=" rightDiv">
        <a asp-page="./Index" asp-route-churchId="@Request.Query["churchId"]">Return to Church Goals</a>
    </div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ChurchGoal.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ChurchGoal.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ChurchGoal.GoalDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ChurchGoal.GoalDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ChurchGoal.NumberOfDoorsGoal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ChurchGoal.NumberOfDoorsGoal)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ChurchGoal.NumberOfConnections)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ChurchGoal.NumberOfConnections)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ChurchGoal.NumberOfDoorsGoal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ChurchGoal.NumberOfDoorsGoal)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ChurchGoal.NumberOfGreetsGoal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ChurchGoal.NumberOfGreetsGoal)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="ChurchGoal.ChurchGoalId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        
    </form>
</div>

Pages/ChurchGoals/Edit.cshtml
@page
@model outreach3.Pages.ChurchGoals.EditModel

@{
    ViewData["Title"] = "Edit";
}


<h4>Edit Church Goal</h4>
<hr />
<div class="rightDiv">
    <a asp-page="./Index" asp-route-churchId="@Request.Query["churchId"]">Return to Goals List</a>
</div>

<form method="post">
    <div class="divRounded">
        <table>
            <tr>
                <td class="tdWide">
                    <div class="row">
                        <div class="col-md-8">

                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="ChurchGoal.ChurchGoalId" />

                            <div class="form-group">
                                <label asp-for="ChurchGoal.Name" class="control-label"></label>
                                <input asp-for="ChurchGoal.Name" class="form-control" />
                                <span asp-validation-for="ChurchGoal.Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ChurchGoal.StartDate" class="control-label"></label>
                                <input asp-for="ChurchGoal.StartDate" class="form-control" />
                                <span asp-validation-for="ChurchGoal.StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ChurchGoal.GoalDate" class="control-label"></label>
                                <input asp-for="ChurchGoal.GoalDate" class="form-control" />
                                <span asp-validation-for="ChurchGoal.GoalDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ChurchGoal.NumberOfDoorsGoal" class="control-label"></label>
                                <input asp-for="ChurchGoal.NumberOfDoorsGoal" readonly class="form-control" />
                                <span asp-validation-for="ChurchGoal.NumberOfDoorsGoal" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ChurchGoal.NumberOfGreetsGoal" class="control-label"></label>
                                <input asp-for="ChurchGoal.NumberOfGreetsGoal" readonly class="form-control" />
                                <span asp-validation-for="ChurchGoal.NumberOfGreetsGoal" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <table>
                                    <tr>
                                        <td>
                                            <input type="submit" value="Reset" class="btn btn-primary" asp-route-churchId="@Request.Query["churchId"]" asp-route-churchGoalId="@Request.Query["churchGoalId"]" asp-page-handler="Reset" />
                                        </td>
                                        <td>
                                            <input type="submit" value="Save" class="btn btn-primary" />
                                        </td>
                                    </tr>
                                </table>
                            </div>

                        </div>
                    </div>
                </td>
                <td class="tdWide">
                    <div class="row">
                        <div style='width:400px;padding:10px;border:2px outset gray;color:red;display:@Model.DisplayError;font-weight:bold;'>@Model.Error

                            <div class="rightDiv">
                                <input type="submit" asp-page="./Edit" formmethod="post" asp-page-handler="OK" value="OK" asp-route-churchGoalId="@Request.Query["churchGoalId"]" asp-route-churchId="@Request.Query["churchId"]" />
                            </div>
                        </div>
                        <label asp-for="AllMissions" class="control-label">Missions</label><br />
                        <select style="width:400px;" size="10" name="allMissions" asp-items="Model.AllMissions">
                        </select>

                        <div>
                            <div>
                                <table>
                                    <tr class="align-content-md-stretch">
                                        <td>
                                            <input asp-page="./Edit" asp-route-churchGoalId="@Request.Query["churchGoalId"]" asp-route-churchId="@Request.Query["churchId"]" name="btnAdd" asp-page-handler="Add" method="post" type="submit" value="Add" class="btn btn-primary" />
                                        </td>
                                        <td>
                                            <input asp-page="./Edit" asp-route-churchGoalId="@Request.Query["churchGoalId"]" asp-route-churchId="@Request.Query["churchId"]" name="btnDelete" asp-page-handler="Delete" method="post" type="submit" value="Remove" class="btn btn-primary" />
                                        </td>
                                    </tr>
                                </table>

                            </div>
                        </div>
                        <div>
                            <div>

                                <label asp-for="GoalMissions" class="control-label"></label><br />
                                <select style="width:400px;" size="10" name="goalMissions" asp-items="Model.GoalMissions"></select>
                            </div>
                        </div>



                    </div>
                </td>
            </tr>
        </table>

    </div>
</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Pages/ChurchGoals/Index.cshtml
@page
@model outreach3.Pages.ChurchGoals.IndexModel

<h4>Church Goals</h4>
<p>
   
    <div class="rightDiv">
        <a asp-page="../Churches/ChurchesMenu" asp-route-churchId="@Request.Query["churchId"]">Return to Church Menu</a>
    </div> 
    <a asp-page="Create" asp-route-churchId="@Request.Query["churchId"]">Create New</a>
    
    <form method="post">
        <input type="submit" class="linkInput" style="display:@Model.EmailNotificationAdd;" asp-page-handler="AddEmail" asp-route-churchId="@Request.Query["churchId"]" value="Add Weekly Email Notifications" name="addEmail" />
        <input type="submit" class="linkInput" style="display:@Model.EmailNotificationRemove;" asp-page-handler="RemoveEmail" asp-route-churchId="@Request.Query["churchId"]" value="Remove Weekly Email Notifications" name="removeEmail" />

    </form>
    
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ChurchGoals[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChurchGoals[0].StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChurchGoals[0].GoalDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChurchGoals[0].NumberOfDoorsGoal)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.ChurchGoals[0].NumberOfDoors)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.ChurchGoals) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GoalDate)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.NumberOfDoorsGoal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfDoors)
            </td>
            <td>
                    <a asp-page="./Details" asp-route-churchId="@item.ChurchId" asp-route-churchGoalId="@item.ChurchGoalId">Details</a>
                    @if (User.IsInRole("ChurchAdmin") || User.IsInRole("Admin") || User.IsInRole("GoalEditor"))
                {
                        <a asp-page="./Edit" asp-route-churchId="@item.ChurchId" asp-route-churchGoalId="@item.ChurchGoalId">Edit</a>
                        <a asp-page="./Delete" asp-route-churchGoalId="@item.ChurchGoalId" asp-route-churchId="@item.ChurchId">Delete</a>
                }
            </td>
        </tr>
}
    </tbody>
</table>