Pages/Admin/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class CreateModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public CreateModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Member Member { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Members == null || Member == null)
            {
                return Page();
            }

            _context.Members.Add(Member);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class DeleteModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public DeleteModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Member Member { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FirstOrDefaultAsync(m => m.MemberId == id);

            if (member == null)
            {
                return NotFound();
            }
            else 
            {
                Member = member;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }
            var member = await _context.Members.FindAsync(id);

            if (member != null)
            {
                Member = member;
                _context.Members.Remove(Member);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Admin
{
    public class DetailsModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public DetailsModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public Member Member { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }
            else 
            {
                Member = member;
            }
            return Page();
        }
    }
}

Pages/ChurchGoals/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using outreach3.Data;
using outreach3.Data.Ministries;

namespace outreach3.Pages.ChurchGoals
{
    public class EditModel : PageModel
    {
        private readonly outreach3.Data.ApplicationDbContext _context;

        public EditModel(outreach3.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ChurchGoal ChurchGoal { get; set; } = default!;

        public string DisplayError
        {
            get 
            {
                if(Error == "")
                {
                    return "none";
                }
                return "inline-block";
            }
        }
        public string Error { get; set; } = "";

    
      
        public string ErrorVisibility { get; set; } = "hidden";

        public List<SelectListItem> AllMissions { get; set; }
        public List<SelectListItem> GoalMissions { get; set; }

        public async Task<IActionResult> OnGetAsync(int? churchId, int? churchGoalId)
        {
            if (churchId == null || _context.ChurchGoals == null)
            {
                return NotFound();
            }

            var churchgoal =  await _context.ChurchGoals.FirstOrDefaultAsync(m => m.ChurchId == churchId && m.ChurchGoalId==churchGoalId);
            if (churchgoal == null)
            {
                return NotFound();
            }
            
            //churchgoal.ChurchId = Convert.ToInt32(Request.Query["churchId"]);
            ChurchGoal = churchgoal;

            AllMissions = _context.Missions.Where(m => m.ChurchId == churchId).Select(a =>
                                 new SelectListItem
                                 {
                                     Value = a.MissionId.ToString(),
                                     Text = a.Name
                                 }).ToList();


            GoalMissions = _context.Missions.Where(m => m.ChurchId == churchId && m.GoalId==churchgoal.ChurchGoalId).Select(a =>
                                 new SelectListItem
                                 {
                                     Value = a.MissionId.ToString(),
                                     Text = a.Name
                                 }).ToList();
            return Page();
        }




        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(ChurchGoal).State = EntityState.Modified;

            try
            {
                ChurchGoal.ChurchId = Convert.ToInt32(Request.Query["churchId"]);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ChurchGoalExists(ChurchGoal.ChurchGoalId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index", new { churchId = Request.Query["churchId"] });
        }

        public async Task<IActionResult> OnPostAddAsync(int churchGoalId)
        {
            var missionId = Convert.ToInt32(Request.Form["allMissions"]);
            if(missionId==0)
            {
                Error = "Please select a mission for this goal.";
                return null;
            }
            var missionGoalId = _context.Missions.FirstOrDefaultAsync(m => m.MissionId == missionId).Result.GoalId;

            if (missionGoalId != 0)
            {
                Error = "This Mission already belongs to a goal.";
                return null;
            }

            _context.Missions.FirstOrDefault(m => m.MissionId == missionId).GoalId = ChurchGoal.ChurchGoalId;
            ChurchGoal = _context.ChurchGoals.Where(m => m.ChurchGoalId == churchGoalId).FirstOrDefault();
            ChurchGoal.NumberOfDoorsGoal = ChurchGoal.NumberOfDoorsGoal + _context.Residents.Where(m => m.MissionId == missionId).Count();
            ChurchGoal.NumberOfGreetsGoal = ChurchGoal.NumberOfDoorsGoal / 4;
            await _context.SaveChangesAsync();    
            return RedirectToPage("Edit", new { churchId = Request.Query["churchId"], churchGoalId = Request.Query["churchGoalId"] });
        }
        public async Task<IActionResult> OnPostDeleteAsync(int churchGoalId)
        {
            var missionId = Convert.ToInt32(Request.Form["allMissions"]);

            if(missionId == 0)
            {
                Error = "Please select a mission from the Missions List (Top List).";
                return null;

            }

            if (missionId != 0)
            {
                var missionGoalId = _context.Missions.FirstOrDefaultAsync(m => m.MissionId == missionId).Result.GoalId;

                if (missionGoalId != churchGoalId)
                {
                    Error = "This Mission cannot be removed, it is not part of this goal.";
                    return null;
                }


                _context.Missions.FirstOrDefaultAsync(m => m.MissionId == missionId).Result.GoalId = 0;
                ChurchGoal = _context.ChurchGoals.Where(m => m.ChurchGoalId == churchGoalId).FirstOrDefault();
                ChurchGoal.NumberOfDoorsGoal = ChurchGoal.NumberOfDoorsGoal - _context.Residents.Where(m => m.MissionId == missionId).Count();
                ChurchGoal.NumberOfGreetsGoal = ChurchGoal.NumberOfDoorsGoal / 4;
            }

            await _context.SaveChangesAsync();
            return RedirectToPage("Edit", new { churchId = Request.Query["churchId"], churchGoalId = Request.Query["churchGoalId"] });
        }
        public async Task<IActionResult> OnPostResetAsync(int churchGoalId)
        {
            
            foreach(var mission in _context.Missions.Where(m=>m.GoalId==churchGoalId))
            {
                mission.GoalId = 0;
            }

            ChurchGoal = _context.ChurchGoals.Where(m => m.ChurchGoalId == churchGoalId).FirstOrDefault();
            ChurchGoal.NumberOfDoorsGoal = 0;
            ChurchGoal.NumberOfGreetsGoal = 0;
            await _context.SaveChangesAsync();
            return RedirectToPage("Edit", new { churchId = Request.Query["churchId"], churchGoalId = Request.Query["churchGoalId"] });
        }

        public async Task<IActionResult> OnPostOKAsync(int churchGoalId, int churchId)
        {           
            return RedirectToPage("Edit", new { churchId, churchGoalId });
        }

        private bool ChurchGoalExists(int id)
        {
          return (_context.ChurchGoals?.Any(e => e.ChurchGoalId == id)).GetValueOrDefault();
        }
    }
}

Pages/Churches/ChurchRegistration.cshtml.cs
using Azure.Core;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Options;
using outreach3.Data;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Diagnostics;
using System.Net.Mail;
using outreach3.Data.Ministries;

namespace outreach3.Pages.Churches
{
    public class ChurchRegistration : PageModel
    {
        private IWebHostEnvironment _webHostEnvironment;
        private readonly ApplicationDbContext _context;
        private IServiceProvider _serviceProvider;
        public ChurchRegistration(ApplicationDbContext context, IServiceProvider serviceProvider, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _serviceProvider = serviceProvider;
            _webHostEnvironment = webHostEnvironment;
        }

        public IList<Church> Churches { get; set; } = default!;

        public Church Church { get; set; } = new Church();

        public SelectList Members { get; set; }

        public int MemberId = 0;

        public async Task OnGetAsync(string email, string userName)
        {
            //Create the Member
            await Init(email, userName);
        }



        private async Task Init(string email, string userName)
        {

            if (!_context.Members.Any(m => m.Email == email))
            {
                var member = new Member();
                member.Email = email;
                member.Name = userName;
                await _context.Members.AddAsync(member);
                await _context.SaveChangesAsync();
            }


            MemberId = _context.Members.FirstOrDefault(m => m.Email == email).MemberId;
            Churches = _context.Churches.ToList();
        }

        public async Task<IActionResult> OnPostJoinMemberToChurchAsync(int churchId)
        {
            var userManager = _serviceProvider.GetRequiredService<UserManager<IdentityUser>>();
            var email = userManager.Users.FirstOrDefault(u => u.UserName == User.Identity.Name).Email;
            Init(email, User.Identity.Name);
            Churches = _context.Churches.ToList();
            var joinId = Request.Form["JoinIds"];
            if (joinId != 0)
            {
                Church = _context.Churches.FirstOrDefault(c => c.ChurchId == Convert.ToInt32(joinId));
                _context.Members.FirstOrDefault(m => m.Email == email).ChurchId = Convert.ToInt32(joinId);
                await _context.SaveChangesAsync();
            }

            await SendEmail(email, $"Outreach Ministry", $"Thank you for joining the Outreach Ministry team for {Church.ChurchFullName}.  " +
                $"Please contact your Church Administrator if you have any questions.  If you are uncertain who that is, " +
                $"please send inquiry to <a href='mailto:cgbrewer2@comcast.net'> Outreach Missions</a>.<br /><br />Thank you.");

            return RedirectToPage("../Churches/Index");
        }


        [BindProperty]
        public Church ChurchForCreation { get; set; } = default!;
        public async Task<IActionResult> OnPostCreateChurchAsync()
        {
            _context.Churches.Add(ChurchForCreation);

            await _context.SaveChangesAsync();

            var userManager = _serviceProvider.GetRequiredService<UserManager<IdentityUser>>();
            var email = userManager.Users.FirstOrDefault(u => u.UserName == User.Identity.Name).Email;


            await SendEmail(email, "Outreach3 Ministry Church Registration", $"Thank you for creating a church in the Outreach Ministry site for {ChurchForCreation.ChurchFullName}.  " +
                "Please allow up to 72 hours prior to church access becoming avalable.<br />" +
                $"Please send any inquiries to <a href='mailto:cgbrewer2@comcast.net'> Outreach Missions</a>.<br /><br />Thank you.");

            await SendEmail("cgbrewer2@comcast.net", "Outreach Ministry Church Creation.", $"{email} has created the church {ChurchForCreation.ChurchFullName}.");





            return RedirectToPage("../Churches/Create");
        }

        public async Task<bool> SendEmail(string to, string subject, string body)
        {
            if (!_webHostEnvironment.IsDevelopment())
            {
                try
                {
                    var status = Activity.Current.StatusDescription;

                    //Initialize WebMail helper
                    MailMessage msg = new MailMessage();
                    msg.From = new MailAddress("postmaster@wfwcoutreach.com");
                    msg.To.Add(new MailAddress(to));
                    msg.Subject = subject;
                    msg.Body = body;

                    SmtpClient smtpClient = new SmtpClient("m06.internetmailserver.net", Convert.ToInt32(587));
                    System.Net.NetworkCredential credentials = new System.Net.NetworkCredential("postmaster@wfwcoutreach.com", "Tlimlamsps@&ok100");
                    smtpClient.Credentials = credentials;
                    smtpClient.EnableSsl = true;
                    smtpClient.SendAsync(msg.From.ToString(), msg.To.ToString(), msg.Subject.ToString(), msg.Body.ToString(), null);
                }
                catch (Exception ex)
                {
                    return false;
                }
                return true;
            }
            return false;
        }
    }
}

Pages/Churches/ChurchesMenu.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace outreach3.Pages.Churches
{
    public class ChurchesMenuModel : PageModel
    {
        private readonly Data.ApplicationDbContext _context;
        
        public ChurchesMenuModel(Data.ApplicationDbContext context)
        {
            _context = context;            
        }

        public List<int> MissionIds { get; set; }
        public void OnGet()
        {
            var userName = User.Identity.Name;
            var member = _context.Members.FirstOrDefault(m=>m.Name == userName);

            MissionIds = _context.Missions.Where(c=>c.ChurchId == member.ChurchId).Select(s=>s.MissionMapId).ToList();

        }
    }
}

Pages/Churches/ChurchMap.cshtml
@page
@model outreach3.Pages.ChurchMap.EditModel

@{
    ViewData["Title"] = "Map";
}

<script>
    //Global Variables
    var mapData = { lat:30.33367926935318, lng: -81.65979765501024 };
    var mapZoom = 10;
    var map;  
    var mapMarkers = new Array();
    var geocoder;
    var infoWindow;



    var markerCounter = 1;
    var selectedMarker;
     var mapMarkerData="";
     var movedMapMarkers="";
    /*****************************Initialize the Map************************************/
    async function initMap() 
    {

         /*******Create GeoCoder Objects******* */
        geocoder = new google.maps.Geocoder;
        infoWindow= new google.maps.InfoWindow();
        map = new google.maps.Map(document.getElementById('map'), {
            zoom: 11,
            mapTypeId: 'hybrid'
        });

        document.addEventListener('contextmenu', function (e) { e.preventDefault(); });
        var centerData = mapData;
        var mapCenter = JSON.stringify(centerData);
        var mapCenterObj = JSON.parse(mapCenter);
        var myLat = mapCenterObj.lat;
        var myLong = mapCenterObj.lng;
        
        map.setCenter(new google.maps.LatLng(myLat, myLong));

        
        /******Insert Markers from database******/
        @foreach (var marker in Model.Markers.ToList().OrderBy(m=>m.Number))
        {       
            <text>var slatlng = "@marker.LatLng"; </text>       
            <text>var address = "@marker.Title"; </text>
            <text>var markerNumber = @marker.Number.ToString(); </text>
            <text>SetMarkersInMapOnLoad(slatlng); </text>        
        }

        /***************Set Map Properties *******************/
        map.setTilt(parseInt(document.getElementById("inpMapTilt").value));
        map.setHeading(parseInt(document.getElementById("inpMapHeading").value));

        /*****************Add Click Event******************************/
        google.maps.event.addListener(map, 'click', function (event) {
            addMarker(event.latLng, false);
        });
        /*****************Add Center Changed Event******************************/
        google.maps.event.addListener(map, 'center_changed', function () {
            UpdateCoordinates(map.getCenter());
        });
        /*****************Add zoom Event******************************/
        google.maps.event.addListener(map, 'zoom_changed', function () {
            UpdateZoom(map.getZoom());
        })
    }
    /******************************************************************************* */
   

    function SetMarkersInMapOnLoad(latlng) 
    {      
      var latlngParts = latlng.replace("(", "").replace(")", "").split(",");        
      var slatlng = JSON.parse("{\"lat\": " + latlngParts[0].toString() + ", \"lng\": " + latlngParts[1].toString() + "}"); 
      addMarker(slatlng, true);
     
    }

    
     function  addMarker(location, canDelete) 
     {    
         var number = mapMarkers.length + 1;
         /*  1:  Set Color and Label  */
                  
         var oneToEight = number;
         while(oneToEight > 8)
         {
             oneToEight-=8;
         }         
        /* 2:  Create Marker  */
         var marker = new google.maps.Marker({
            position: location,                       
            icon: "https://wfwcoutreach.com/wwwroot/Images/" + markColor + ".png",
            forecolor: foreColor,
            draggable: false,
            label: ".",   
            tag: number,
            map: map
        }); 
        //  3: Geocode the infowindow        
        geocodeLatLng(location, marker);        
          //  5: Add the Marker to the collection
         mapMarkers.push(marker);
         
    }

     function geocodeLatLng(latlng, marker) 
    {        
        geocoder
            .geocode({ location: latlng })
            .then((response) => {
                if (response.results[0]) {
                    infoWindow.setContent(response.results[0].formatted_address);
                    marker.setTitle(response.results[0].formatted_address);

                } else {
                    window.alert("No results found");
                }
            })
            .catch((e) => window.alert("Geocoder failed due to: " + e));
    }
    
    var markColor = "blue";
    var foreColor = "blue";
    
   
                     
        

</script>
<form method="post">
   
    <div style="text-align:right;"><a asp-page="./ChurchesMenu"  asp-route-churchId=@Request.Query["churchId"] >Return to Menu</a></div>
     <hr />

<p class="shadow">This map is not intended to be functional, it simply displays all of the markers for every mission of the church.  Zoom in and Pan to the area(s) where the missions are located.</p>

     <div id="map" name="map" style="font-size:1px;border: 2px;width:1024px;height:1024px; background-color:blue"></div>     
  
</form>
<script src="@Model.GetScriptWithAPIKey()" async defer></script>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Pages/Churches/ChurchRegistration.cshtml
@page
@model             ChurchRegistration

@{
    ViewData["Title"] = "Church Registration";
}




<h5>Please select the church(s) you are affiliated with.  The Church administrator will need to approve the request prior to access.
    <p>If your church is not listed, please contact the <a href="mailto:cgbrewer2@comcast.net">site administrator</a> for a church administrator account.</p>
</h5>
<form method="post">

    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>
                    @Html.DisplayNameFor(model => model.Churches[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Churches[0].ChurchAddress)
                </th>

                <th>
                   Select Church
                </th>
               

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Churches)
            {
                <tr>                
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => @item.ChurchFullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ChurchAddress)
                    </td>
                    <td>
                        <input onchange="JoinChurch('@item.ChurchId');" type="radio" name="checkBoxChurchMember" value="@item.ChurchId" required />
                    </td>  
                </tr>
            }




        </tbody>
    </table>
    <input type="submit" name="inpJoin" asp-page-handler="JoinMemberToChurch" asp-route-memberId="@Model.MemberId">
    <input type="hidden" name="JoinIds" />
</form>
<hr />
<label class="shadow">Request to <a asp-page="../Churches/Create" asp-route-memberId="@Model.MemberId">Create</a> a new Church as the Church Administrator</label>


<script>
   
    function JoinChurch(id) {

        var joinIds = "";
        for (var i = 0; i < document.getElementsByName("checkBoxChurchMember").length; i++) {

            if (document.getElementsByName("checkBoxChurchMember")[i].checked.toString() == "true") {
                var newValue = document.getElementsByName("checkBoxChurchMember")[i].value;
                var joinIds = newValue;

            }
        }
        document.getElementsByName("JoinIds")[0].value = joinIds;

    }
</script>

Pages/Churches/ChurchesMenu.cshtml
@page
@model outreach3.Pages.Churches.ChurchesMenuModel
@{

    <h4> Church Status Menu</h4>
    <div style="text-align:right;"><a asp-page="../Churches/Index" asp-route-churchId="@Request.Query["churchId"]">Return to Churches List</a></div>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <td>
                    <a asp-page="/Churches/ChurchMap" asp-route-churchId="@Request.Query["ChurchId"]">Church Missions Map</a>
                </td>

                <td>
                    <a asp-page="/Churches/Stats" asp-route-churchId="@Request.Query["ChurchId"]">Mission Statistics</a>
                </td>


                <td>
                    <a asp-page="../ChurchGoals/Index" asp-route-churchId="@Request.Query["ChurchId"]">Church Goals</a>
                </td>

            </tr>

        </tbody>
    </table>
}

Pages/Churches/Edit.cshtml
@page
@model             EditModel

@{
    ViewData["Title"] = "Edit";
}



<h4>@Model.Church.Name</h4>
<div style="text-align:right">
    <a asp-page="./Index">Return to Church List</a>
</div>
<hr />
<table class="modal-fullscreen">
    <tbody>
        <tr>
            <td>
                <div class="row">
                    <div class="col-md-4">
                        <form method="post">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Church.ChurchId" />
                            <div class="form-group">
                                <label asp-for="Church.Name" class="control-label"></label>
                                <input asp-for="Church.Name" class="form-control" />
                                <span asp-validation-for="Church.Name" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Church.ChurchFullName" class="control-label"></label>
                                <input asp-for="Church.ChurchFullName" class="form-control" />
                                <span asp-validation-for="Church.ChurchFullName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Church.ChurchAddress" class="control-label"></label>
                                <input asp-for="Church.ChurchAddress" class="form-control" />
                                <span asp-validation-for="Church.ChurchAddress" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Church.ChurchPhone" class="control-label"></label>
                                <input asp-for="Church.ChurchPhone" class="form-control" />
                                <span asp-validation-for="Church.ChurchPhone" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Church.PastorsName" class="control-label"></label>
                                <input asp-for="Church.PastorsName" class="form-control" />
                                <span asp-validation-for="Church.PastorsName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Save" class="btn btn-primary" />
                            </div>
                        </form>
                    </div>
                    <div class="col-md-6">

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="row">
                            <div>
                                <form method="post">
                                    <label asp-for="AllUsers" class="control-label"></label><br />
                                    <select style ="width:300px;" size="10" name="allUsers" asp-items="Model.AllUsers">
                                    </select>

                                    <div>
                                        <div>
                                            <table>
                                                <tr class="align-content-md-stretch">
                                                    <td>
                                                        <input asp-page="./Edit" name="btnAdd" asp-page-handler="Add" method="post" type="submit" value="Add" class="btn btn-primary" />
                                                    </td>
                                                    <td>
                                                        <input asp-page="./Edit" name="btnDelete" asp-page-handler="Delete" method="post" type="submit" value="Remove" class="btn btn-primary" />
                                                    </td>
                                                </tr>
                                            </table>

                                        </div>
                                    </div>
                                    <div>
                                        <div>

                                            <label asp-for="SiteUsers" class="control-label"></label><br />
                                            <select style="width:300px;" size="10" name="siteUsers" asp-items="Model.SiteUsers"></select>
                                        </div>
                                    </div>

                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </td>
        </tr>

    </tbody>

</table>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Pages/Churches/ErrorTest.cshtml
@page
@model outreach3.Pages.Churches.ErrorTestModel
@{
}